api_platform:
    title: Welcome to jonnyeom.com APIs
    version: 1.0.0

    # Enable the docs
    enable_docs: true

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    doctrine:
        enabled: false
    swagger:
        versions: [3]
    http_cache:
        # To make all responses public by default.
        public: true
        invalidation:
            # To enable the tags-based cache invalidation system.
            enabled: true

    formats:
        jsonld: [ 'application/ld+json' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
