name: app

type: php:8.1

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e

        symfony-deploy
