services:
  - type: web
    name: jonnyeom-com
    runtime: docker
    dockerfilePath: ./docker/Dockerfile
    port: 10000
    preDeployCommand: "php bin/console doctrine:migrations:migrate --no-interaction"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jonnyeom-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: '^https?://(localhost|127\.0\.0\.1|www\.jonnyeom\.com)(:[0-9]+)?$'
      - key: OAUTH_STRAVA_CLIENT_ID
        sync: false
      - key: OAUTH_STRAVA_CLIENT_SECRET
        sync: false

databases:
  - name: jonnyeom-db
    plan: free
    databaseName: jonnyeom
    user: jonnyeom
