<?php

declare(strict_types=1);

namespace App\Tests\Model\Strava;

use App\Model\Strava\DailyStat;

/** @phpstan-import-type Activity from DailyStat */
trait UseSampleWeeklyActivities
{
    /** @return array<int, Activity> */
    public function getSampleWeeklyActivities(): array
    {
        return [
            // 5k run.
            [
                'resource_state' => 2,
                'athlete' => ['id' => 12345678, 'resource_state' => 1],
                'name' => '5k Run at 8min/mi pace',
                'distance' => 5000,
                'moving_time' => 1491,
                'elapsed_time' => 1491,
                'total_elevation_gain' => 15.0,
                'type' => 'Run',
                'sport_type' => 'Run',
                'workout_type' => 0,
                'id' => 10138785832,
                'start_date' => '2023-10-31T21:40:23Z',
                'start_date_local' => '2023-10-31T17:40:23Z',
                'timezone' => '(GMT-05:00) America/New_York',
                'utc_offset' => -14400.0,
                'location_city' => null,
                'location_state' => null,
                'location_country' => null,
                'achievement_count' => 0,
                'kudos_count' => 3,
                'comment_count' => 0,
                'athlete_count' => 1,
                'photo_count' => 0,
                'map' => ['id' => 'a10138785832', 'summary_polyline' => '', 'resource_state' => 2],
                'trainer' => false,
                'commute' => false,
                'manual' => false,
                'private' => false,
                'visibility' => 'everyone',
                'flagged' => false,
                'gear_id' => null,
                'start_latlng' => [],
                'end_latlng' => [],
                'average_speed' => 2.711,
                'max_speed' => 3.952,
                'average_cadence' => 86.4,
                'average_temp' => 20,
                'has_heartrate' => true,
                'average_heartrate' => 151.6,
                'max_heartrate' => 164.0,
                'heartrate_opt_out' => false,
                'display_hide_heartrate_option' => true,
                'elev_high' => 100.8,
                'elev_low' => 59.8,
                'upload_id' => 10860019649,
                'upload_id_str' => '10860019649',
                'external_id' => 'garmin_ping_302468556119',
                'from_accepted_tag' => false,
                'pr_count' => 0,
                'total_photo_count' => 0,
                'has_kudoed' => false,
            ],
            // 10k run.
            [
                'resource_state' => 2,
                'athlete' => [ 'id' => 12345678, 'resource_state' => 1 ],
                'name' => '10k Run at 9min/mi pace',
                'distance' => 10000,
                'moving_time' => 3169,
                'elapsed_time' => 3469,
                'total_elevation_gain' => 82.0,
                'type' => 'Run',
                'sport_type' => 'Run',
                'workout_type' => 0,
                'id' => 10150030032,
                'start_date' => '2023-11-02T20:56:01Z',
                'start_date_local' => '2023-11-02T16:56:01Z',
                'timezone' => '(GMT-05:00) America/New_York',
                'utc_offset' => -14400.0,
                'location_city' => null,
                'location_state' => null,
                'location_country' => null,
                'achievement_count' => 0,
                'kudos_count' => 3,
                'comment_count' => 0,
                'athlete_count' => 1,
                'photo_count' => 0,
                'map' => [ 'id' => 'a10150030032', 'summary_polyline' => '', 'resource_state' => 2 ],
                'trainer' => false,
                'commute' => false,
                'manual' => false,
                'private' => false,
                'visibility' => 'everyone',
                'flagged' => false,
                'gear_id' => null,
                'start_latlng' => [],
                'end_latlng' => [],
                'average_speed' => 2.644,
                'max_speed' => 3.74,
                'average_cadence' => 84.9,
                'average_temp' => 18,
                'has_heartrate' => true,
                'average_heartrate' => 148.0,
                'max_heartrate' => 168.0,
                'heartrate_opt_out' => false,
                'display_hide_heartrate_option' => true,
                'elev_high' => 155.4,
                'elev_low' => 112.6,
                'upload_id' => 10871826664,
                'upload_id_str' => '10871826664',
                'external_id' => 'garmin_ping_302798808586',
                'from_accepted_tag' => false,
                'pr_count' => 0,
                'total_photo_count' => 0,
                'has_kudoed' => false,
            ],
        ];
    }
}
